create table if not exists public.users (
  openid text primary key,
  display_name text not null default '',
  organizations text[] not null default '{}',
  role text not null default 'unverified' check (role in ('unverified', 'normal', 'admin', 'superadmin', 'chairman')),
  dismissed boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.operations (
  id bigint generated by default as identity primary key,
  submit_time timestamptz not null default timezone('utc', now()),
  item_id text not null,
  item_name text not null,
  operation text not null check (operation in ('入库', '出库', '物资增添', '部分出库')),
  organization text not null,
  quantity integer not null check (quantity > 0),
  operation_time text not null,
  operator text not null,
  submitter text not null,
  operator_openid text not null references public.users(openid)
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  item_id text not null,
  item_name text not null,
  organization text not null,
  quantity integer not null check (quantity > 0),
  last_operation text not null,
  last_operator text not null,
  last_operation_time text not null,
  notes text not null default '',
  updated_at timestamptz not null default timezone('utc', now()),
  unique (item_id, organization)
);

create table if not exists public.config (
  key text primary key,
  organizations text[] not null default '{}',
  operators text[] not null default '{}',
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mini_sessions (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  openid text not null references public.users(openid) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists operations_submit_time_idx on public.operations (submit_time desc);
create index if not exists operations_item_org_idx on public.operations (item_id, organization);
create index if not exists inventory_item_idx on public.inventory (item_id);
create index if not exists users_role_idx on public.users (role);
create index if not exists sessions_openid_idx on public.mini_sessions (openid);
create index if not exists sessions_expires_at_idx on public.mini_sessions (expires_at);

create or replace function public.ensure_default_config()
returns public.config
language plpgsql
as $$
declare
  cfg public.config;
begin
  insert into public.config (key, organizations, operators, updated_at)
  values (
    'settings',
    array[
      '学生会',
      '团委',
      '学生发展中心',
      '社区管理委员会',
      '"橙光"志愿服务队',
      '足球队器材存放',
      '篮球队器材存放',
      '其他体育器材存放',
      '备用储物箱'
    ]::text[],
    array[]::text[],
    timezone('utc', now())
  )
  on conflict (key) do nothing;

  select * into cfg from public.config where key = 'settings';
  return cfg;
end;
$$;

create or replace function public.apply_operation(
  p_item_id text,
  p_item_name text,
  p_operation text,
  p_organization text,
  p_quantity integer,
  p_operation_time text,
  p_operator text,
  p_operator_openid text
)
returns void
language plpgsql
as $$
declare
  existing_row public.inventory;
  new_qty integer;
  now_utc timestamptz := timezone('utc', now());
begin
  if p_item_id is null or btrim(p_item_id) = '' then
    raise exception '缺少必填字段: itemId';
  end if;
  if p_item_name is null or btrim(p_item_name) = '' then
    raise exception '缺少必填字段: itemName';
  end if;
  if p_operation is null or btrim(p_operation) = '' then
    raise exception '缺少必填字段: operation';
  end if;
  if p_organization is null or btrim(p_organization) = '' then
    raise exception '缺少必填字段: organization';
  end if;
  if p_quantity is null or p_quantity <= 0 then
    raise exception '数量必须为正整数';
  end if;
  if p_operation_time is null or p_operation_time !~ '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$' then
    raise exception '时间格式必须为 YYYY-MM-DD HH:MM';
  end if;
  if p_operation not in ('入库', '出库', '物资增添', '部分出库') then
    raise exception '无效的操作类型: %', p_operation;
  end if;

  select *
  into existing_row
  from public.inventory
  where item_id = p_item_id and organization = p_organization
  for update;

  if p_operation = '入库' and existing_row.id is not null then
    raise exception '物资 % 已存在，请使用"物资增添"操作', p_item_id;
  end if;

  if p_operation <> '入库' and existing_row.id is null then
    raise exception '物资 % 不存在', p_item_id;
  end if;

  if p_operation = '部分出库' and p_quantity > existing_row.quantity then
    raise exception '出库数量 (%) 超过当前库存 (%)', p_quantity, existing_row.quantity;
  end if;

  insert into public.operations (
    submit_time,
    item_id,
    item_name,
    operation,
    organization,
    quantity,
    operation_time,
    operator,
    submitter,
    operator_openid
  ) values (
    now_utc,
    p_item_id,
    p_item_name,
    p_operation,
    p_organization,
    p_quantity,
    p_operation_time,
    p_operator,
    p_operator,
    p_operator_openid
  );

  if existing_row.id is null then
    insert into public.inventory (
      item_id,
      item_name,
      organization,
      quantity,
      last_operation,
      last_operator,
      last_operation_time,
      notes,
      updated_at
    ) values (
      p_item_id,
      p_item_name,
      p_organization,
      p_quantity,
      p_operation,
      p_operator,
      p_operation_time,
      '',
      now_utc
    );
    return;
  end if;

  new_qty := existing_row.quantity;
  if p_operation = '物资增添' then
    new_qty := existing_row.quantity + p_quantity;
  elsif p_operation = '出库' then
    new_qty := 0;
  elsif p_operation = '部分出库' then
    new_qty := existing_row.quantity - p_quantity;
  end if;

  if new_qty <= 0 then
    delete from public.inventory where id = existing_row.id;
  else
    update public.inventory
    set
      item_name = p_item_name,
      quantity = new_qty,
      last_operation = p_operation,
      last_operator = p_operator,
      last_operation_time = p_operation_time,
      updated_at = now_utc
    where id = existing_row.id;
  end if;
end;
$$;
